######################################################################
# Automatically generated by qmake (3.0) ? 12? 19 14:38:12 2019
######################################################################

TEMPLATE = app
TARGET = pro11
INCLUDEPATH += .

QT += widgets
# Input
HEADERS += calc.h ui_calc_ui.h
FORMS += calc_ui.ui
SOURCES += calc.cpp main.cpp
